### ISSUE TITLE
TWRP for U11+ under Android 8.0 with patch level 20190501

### ISSUE THREAD

**Issue by WanderMax** [sabpprook/android_device_htc_ocm#1]
sabpprook,
I checked your post in xda, found no TWRP for this  patch level and it seems that no update after 181101 patch, could you please help with it ?
**Thank you!**

**Comment by sabpprook** [comment]
Currently vold decrypt is broken in TWRP recovery under Android 9.0 firmware with U11+, therefore twrp.img with patch level 20190501 is useless, you can choice anyone to flash into U11+ which running on Android 9.0 firmware.

If any function not working properly please let me know, e.g. adb shell, touch panel etc.

**Comment by WanderMax** [comment]
@sabpprook my device is still under Android 8.0, I'm not sure whether twrp.img with patch level 181101 can work cross newer patch level or not. Thanks for your reply!

**Comment by WanderMax** [comment]
@sabpprook  I flashed twrp-3.3.1-0-ocm_181101.img via `fastboot flash recovery twrp-3.3.1-0-ocm_181101.img`, then reboot to recovery, it goes into TWRP and touch works fine, only data decrypt function does not work.

**Comment by sabpprook** [comment]
What is the software version and security patch date on your device?

**Comment by WanderMax** [comment]
Model: htc_ocmdtwl (HTCCN701)
Android version: 8.0.0
software version: 1.0.0.2Q4D200 (build number 1.24.1405.24)
security patch date: 20190501

I can help with test in my phone.

**Comment by sabpprook** [comment]
Sorry, Didn't know that China variant have an update as well.
Give it a try please [twrp-3.3.1-0-ocm_190501.img
](https://github.com/sabpprook/android_device_htc_ocm/releases/download/0.0.1/twrp-3.3.1-0-ocm_190501.img)

**Comment by WanderMax** [comment]
@sabpprook  flashed twrp-3.3.1-0-ocm_190501.img, data decrypt function works after boot into new recovery. Thanks!!
